import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Thomas Pegler Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' bg-blue-300'>
        <h1 className=" text-blue-700">
          Hello world!
        </h1>
      </main>
    </>
  )
}
