import React from 'react';
import Head from 'next/head';
import { Header, About } from '../components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Thomas Pegler Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-neutral-800">
        <div className="lines">
          <div className="line" />
          <div className="line" />
          <div className="line" />
        </div>
        <Header />
        <About />
      </main>
    </>
  );
}
